name: Deploy the Site
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  deploy-site:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/docker-deploy