name: Deploy the Site
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Prepare
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Just echo something
        run: echo 'Hello world'